#!/usr/bin/env ruby
# -*- coding: utf-8 -*- 

require 'uri'
#require 'iconv'

if ARGV.size <= 0 
	puts "Usage: ./urldecode url ..."
	exit
end

ARGV.each do |a|
	str=URI.decode("#{a}")
	print str.encode("utf-8", "gbk")
	#print Iconv.conv("utf-8", "gbk",str)
end
